---

- name: "consul-template | generate configuration fragments"
  template:
    src: "consul-template.conf.d/{{ _config }}.j2"
    dest: "/etc/consul/consul-template.conf.d/{{ _config }}"
    owner: "{{ consul_template.user }}"
    group: "{{ consul_template.group }}"
    mode: 0640
    validate: "consul-template -dry -once -config %s"
  # TODO: implement reload signal handler
  # notify: "reload consul-template"
  loop: "{{ consul_template_managed_configs }}"
  loop_control:
    loop_var: _config
