---
- name: "consul-template | create dedicated group"
  group:
    name: "{{ consul_template.user }}"

- name: "consul-template | create dedicated user"
  user:
    name: "{{ consul_template.user }}"
    group: "{{ consul_template.group }}"

- name: "consul-template | create dedicated directories"
  file:
    state: directory
    path: "{{ _directory.value }}"
    owner: "{{ consul_template.user }}"
    group: "{{ consul_template.group }}"
  loop: "{{ consul_template_directories | dict2items }}"
  loop_control:
    label: "{{ _directory.key }}"
    loop_var: _directory


- name: "consul-template | download consul-template"
  unarchive:
    src: "{{ consul_template_release.url }}"
    remote_src: yes
    dest: "{{ consul_template_directories.bin }}"
    creates: "{{ consul_template_directories.bin }}/consul-template"
    owner: "{{ consul_template.user }}"
    group: "{{ consul_template.group }}"
